# Generated by Django 5.0.6 on 2024-06-11 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="court",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="court",
            name="number",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=models.CharField(
                choices=[
                    ("regular", "Zwykła"),
                    ("league", "Liga Format"),
                    ("school", "Szkółka"),
                    ("membership", "Karnety"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("court", "start_time", "end_time")},
        ),
    ]
