# Generated by Django 5.0.6 on 2024-08-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0004_alter_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
