# Generated by Django 5.0.6 on 2024-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="balance_of_hours",
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, default="Oława", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="tennis_club/static/images/tenis_17.png",
                upload_to="profiles/",
            ),
        ),
    ]
